### ISSUE TITLE
Extend the Extension Provider to support Internal Load Balancer Configuration

### ISSUE THREAD

**Issue by afritzler** [onmetal/gardener-extension-provider-onmetal#183]
## Issue

Currently, our `onmetal` Gardener extension provider does not allow the configuration of the internal load balancer in the Kubernetes Cloud Controller Manager for `onmetal`.

This limits the flexibility of our Kubernetes deployments, particularly in environments where internal load balancing is a requirement.

## Proposed Feature

Extend the `onmetal` Gardener extension provider to allow the configuration of internal load balancer usage in the Kubernetes Cloud Controller Manager for `onmetal`. This should allow users to:

- Enable internal load balancing by setting a corresponding annotation to the `Service` object.
- Extend the configuration of the cloud controller manager with the necessary options.

## Tasks

Here are the tasks we'll need to complete to achieve this:

1. Extend the `cloud-provider-config` chart to include a new configuration option for the internal load balancer.
2. Update the Cloud Controller Manager configuration process to use this new setting.
3. Add validation logic to ensure the configuration is valid.
4. Write unit tests for the new features.
5. Update documentation to explain how to use the new feature.

### Acceptance Criteria

- [ ] The extension provider supports the configuration of the internal load balancer.
- [ ] There are unit tests confirming the correct behavior of the new feature.
- [ ] The user documentation is updated to explain how to use the new feature.

Please provide any feedback or additional requirements for this issue.
